micronaut:
  server:
    port: 80
    max-request-size: '100MB'
    multipart:
      max-file-size: '100MB'
  application:
    name: baku
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "fb:dist"
  executors:
    io:
      type: fixed
      nThreads: 75
  ssl:
    port: 443
    enabled: true
    keyStore:
      path: file:/app/ssl/server.pkcs12
      type: PKCS12
      password: GHsLvjmDiAYrpao9

endpoints:
  info:
    enabled: true
    sensitive: false

netty:
  responses:
    file:
      cache-seconds: 604800

application:
  secret:
    admin: "abcdefghijklmnopqrstuvwxyz123456"
    github-token: "foo"

